api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "b2b-tier-discount"
type = "function"
uid = "d3ef4538-f42d-0ae8-ecc6-2fd95d3575e10d020d12"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
