# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7a47c64350b92d852e160a28fd64981a"
name = "Rainytownmedia B2B"
application_url = "https://sb2b.rainytownmedia.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_delivery_customizations,write_delivery_customizations,read_discounts,write_discounts,read_metaobjects,write_metaobjects,read_orders,write_orders,read_payment_customizations,write_payment_customizations,read_products,write_products,read_themes,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://sb2b.rainytownmedia.com/auth/callback",
  "https://sb2b.rainytownmedia.com/api/auth"
]

[app_proxy]
url = "https://sb2b.rainytownmedia.com"
subpath = "b2b"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
