# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c4005f4c51a61366342a87fd93a72e61"
name = "Rainytownmedia B2B"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_delivery_customizations,read_discounts,read_metaobjects,read_orders,read_payment_customizations,read_products,read_themes,write_customers,write_delivery_customizations,write_discounts,write_metaobjects,write_orders,write_payment_customizations,write_products,write_themes"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
