api_version = "2026-01"

[[extensions]]
name = "B2B Payment Customization"
handle = "b2b-payment-customization"
uid = "fd495a53-a660-d2e2-8c71-838fb5d0430ebdab8da4"
type = "function"
description = "Hides or reorders payment options based on customer B2B tags and cart conditions."

  [[extensions.targeting]]
  target = "purchase.payment-customization.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
